version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    # REMOVE OR COMMENT OUT THIS LINE:
    # command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
    restart: on-failure

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=${Database}
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1g
        reservations:
          memory: 512m
    restart: on-failure

networks:
  app-network:
    driver: bridge
volumes:
  mongodb_data:
